name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with: 
       node-version: 20
    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checout the code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
         node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Execute tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true